services:
  - type: web
    name: sweet-boy-bot
    runtime: python:3.11.9
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: BOT_TOKEN
        value: ""
      - key: DEEPSEEK_API_KEY
        value: ""
